name: Projects  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /projects get lambda deploy zip
        uses: postman-open-technologies/projects@main
        with:
            args: zip -qq -r m-s-projects-g.zip projects/get/index.js node_modules
      - name: project get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-projects-g
            zip_file: m-s-projects-g.zip
      - name: /projects post lambda deploy zip
        uses: postman-open-technologies/projects@main
        with:
            args: zip -qq -r m-s-projects-po.zip projects/post/index.js node_modules
      - name: project get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-projects-po
            zip_file: m-s-projects-po.zip
      - name: /projects/{project_id} get lambda deploy zip
        uses: postman-open-technologies/projects@main
        with:
            args: zip -qq -r m-s-projects-project-g.zip projects/project_id/get/index.js node_modules
      - name: project get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-projects-project-g
            zip_file: m-s-projects-project-g.zip
      - name: /projects/{project_id} put lambda deploy zip
        uses: postman-open-technologies/projects@main
        with:
            args: zip -qq -r m-s-projects-project-pu.zip projects/project_id/put/index.js node_modules
      - name: project get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-projects-project-pu
            zip_file: m-s-projects-project-pu.zip
      - name: /projects/{project_id} delete lambda deploy zip
        uses: postman-open-technologies/projects@main
        with:
            args: zip -qq -r m-s-projects-project-d.zip projects/project_id/delete/index.js node_modules
      - name: project get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-projects-project-d
            zip_file: m-s-projects-project-d.zip          
      - name: /projects/{project_id}/tags get lambda deploy zip
        uses: postman-open-technologies/projects@main
        with:
            args: zip -qq -r m-s-projects-project-tags-g.zip projects/project_id/tags/get/index.js node_modules
      - name: projects get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-projects-project-tags-g
            zip_file: m-s-projects-project-tags-g.zip
      - name: /projects/{project_id}/tags post lambda deploy zip
        uses: postman-open-technologies/projects@main
        with:
            args: zip -qq -r m-s-projects-project-tags-po.zip projects/project_id/tags/post/index.js node_modules
      - name: projects get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-projects-project-tags-po
            zip_file: m-s-projects-project-tags-po.zip
      - name: /projects/{project_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/projects@main
        with:
            args: zip -qq -r m-s-projects-project-tags-tag-d.zip projects/project_id/tags/tag_id/delete/index.js node_modules
      - name: projects get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-projects-project-tags-tag-d
            zip_file: m-s-projects-project-tags-tag-d.zip            